### ISSUE TITLE
Amazon S3 ?

### ISSUE THREAD

**Issue by wpexplorer** [syamilmj/Aqua-Resizer#31]
Has anyone been able to get aqua_resizer working for people using Amazon S3 to store their images?

If not, I'm wondering what sort of advice are you giving to your customers who are trying to use your themes which use Aqua Resizer.

Thanks!

**Comment by anteksiler** [comment]
@wpexplorer Have you found a solution for this?

**Comment by wpexplorer** [comment]
Images must be resized and saved to the uploads folder before they are stored on Amazon A3 so they can be used.  Depending on the plugin you are using for amazon S3 some actually work in this way. You can't resize and upload straight to amazon without advanced edits specific for each user.

Personally what I've been doing is providing the ability in my themes to allow users to choose between Aq Resizer or the core post_thumbnail function.
