### ISSUE TITLE
Crop Position

### ISSUE THREAD

**Issue by LimeCuda** [syamilmj/Aqua-Resizer#5]
Timthumb has a way to set the crop alignment
http://www.binarymoon.co.uk/2010/08/timthumb-part-4-moving-crop-location/

so like a=t

Is that possible with this?

**Comment by stefacchio** [comment]
Hello, 
I red this conversation and I need to set crop position.
An example on my website:
http://www.automotostorichetreviglio.it/evento/momenti-di-storia-ed-emozioni-raduno-per-auto-e-moto-storiche-a-san-martino-della-battaglia/?instance_id=60

I would like to have a top crop of featured image event but this plugin only crop central part..
Is there no way to do this?

Thanks
Regards
