### ISSUE TITLE
Aqua Resizer not resizing all images available on the staging server but works perfect in localhost

### ISSUE THREAD

**Issue by DaTechoGeek** [syamilmj/Aqua-Resizer#56]
I am trying to resize the images in the theme files, but it did't print any image to frontend. but it is working fine in the localhost. I didn't understand  what is wrong with my theme files or aqua resizer. I have a website which is having more than 50K images on it, Now i am going to change the theme for the website so i need to regenerate the thumbnails or resize them, i found the aqua resizer is doing it's job very well, and fits my need of the website;

**Comment by renansan** [comment]
It can be a problem with the server image editor.

I had the same problem and solved it by installing GD graphics library and Imagick on the server, running this:

````
sudo apt-get update
sudo apt-get install php5-imagick php5-gd
service apache2 restart
````

I found this solution here: https://wordpress.org/support/topic/wp_get_image_editor-isnot-active
