### ISSUE TITLE
Issue #13 revisited

### ISSUE THREAD

**Issue by Scott8586** [syamilmj/Aqua-Resizer#64]
Hi.  I found issue #13 regarding incorporation of jetpack photon for the presentation of thumbnails.
I tried the solution presented in the comments with one of WPExplorer's themes - 'Adapt' and it works!  I will be incorporating this as a child theme to wpex-adapt.  The only problem was 'apply_filter' should be 'apply_filters'.

Thanks for your help and comments to issue #13

**Comment by syamilmj** [comment]
You're welcome :)
