### ISSUE TITLE
No output for 755 file permission

### ISSUE THREAD

**Issue by wpbean** [syamilmj/Aqua-Resizer#71]
Hi, 

I use this script in one of my plugin. For a server with file permission 755, resized image url not executing. I change wp-content folder file permission to 777 and it's start executing. 

You may know 777 permission is not safe. What to do now?

Thanks in advance

**Comment by syamilmj** [comment]
Standard file permission for WP is 644, 755 is for directory permission.

The script uses WP's built in resize engine, so try checking if native WP resize (e.g. thumbnail) works?
