### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by prosenjit-itobuz** [syamilmj/Aqua-Resizer#73]
I just put the aq_resizer.php. I didn't even call the file warning message showing in sidebar 

Warning: file_get_contents(wp-content/themes/themename/inc/aq_resizer.php): failed to open stream: Permission denied in wp-includes/class-wp-theme.php on line 993

**Comment by syamilmj** [comment]
This is a file permission issue. The following link may be useful - http://stackoverflow.com/questions/18352682/correct-file-permissions-for-wordpress
