### ISSUE TITLE
Saturation Loss with Adobe RGB Images

### ISSUE THREAD

**Issue by stevesearer** [syamilmj/Aqua-Resizer#74]
A few images on my site are saved with Adobe RGB color space which [unfortunately lose saturation when uploaded to a WordPress site] (https://graphpaperpress.com/tips/fix-image-color-saturation-loss-in-wordpress/). 

To counteract this loss of quality, I have installed [ImageMagick Engine] (https://wordpress.org/plugins/imagemagick-engine/) which does a much better job of getting the color correct for the Adobe RGB color space uploads.

Unfortunately it seems like Aqua Resizer uses the default WordPress uploader making any images resized using it lose saturation. This isn't unexpected as it is clearly documented that it is how it works.

I guess I'm wondering if there is any way to have Aqua Resizer work with ImageMagick / ImageMagick Engine?

**Comment by syamilmj** [comment]
WordPress supports ImageMagick out of the box since v3.5 and defaults to GD when it's not available. Check your ImageMagick installation to make sure it is compatible with requirements - https://make.wordpress.org/core/2012/12/06/wp_image_editor-is-incoming/
