### ISSUE TITLE
height and width are mandatory?

### ISSUE THREAD

**Issue by pluus** [syamilmj/Aqua-Resizer#94]
According to 'How to use',

`aq_resize($img_url, $width);`

this is a valid code and the update log(v1.1.7) clearly mentions "either $width or $height is required".  However, if you take a look at the source code(v1.2.1) of aq_resize function,

```

// Validate inputs.
if (!$url)
    throw new Aq_Exception('$url parameter is required');
if (!$width)
    throw new Aq_Exception('$width parameter is required');
if (!$height)
    throw new Aq_Exception('$height parameter is required');

```

this function requires at least three parameters - url, width, and height.  Is it supposed to work this way?

**Comment by menshinobi** [comment]
The ! expression also takes null. If you don't want to pass the height, you should do like this
aq_resize($url, $width, null);

That will make the function not throwing exception. But I agree, the doc should be improved.

**Comment by pluus** [comment]
I see.  Thanks, menshinobi !

**Comment by NautHnim** [comment]
I have the same problem, when I set height to null, it also throw exception.
So, i delete  "if (!$height)..." and i work normally.

**Comment by pluus** [comment]
@NautHnim Hmph, I tried it too and it doesn't work :(

**Comment by mikaelengstrom** [comment]
https://github.com/syamilmj/Aqua-Resizer/pull/65

**Comment by timsamuelsson** [comment]
You can set height = -1, it should work if you want an unspecified height!
